'const fs = require("fs");'  
'const content = `import { getTenantConnection } from "../config/database";'  
'import { CategorySchema, ICategory } from "../models/category.model";'  
'import { AppError } from "../utils/appError";'  
'import { logger } from "../utils/logger";'  
'import { createObjectCsvStringifier } from "csv-writer";'  
'import * as XLSX from "xlsx";'  
''  
'export interface ImportResult {'  
'  success: number;'  
